export interface CVEItem {
  id: string;
  sourceIdentifier: string;
  published: string;
  lastModified: string;
  vulnStatus: string;
  description: string;
}

export interface NVDResponse {
  resultsPerPage: number;
  startIndex: number;
  totalResults: number;
  vulnerabilities: Array<{
    cve: {
      id: string;
      sourceIdentifier: string;
      published: string;
      lastModified: string;
      vulnStatus: string;
      descriptions: Array<{
        lang: string;
        value: string;
      }>;
    };
  }>;
}

export async function fetchDatabase(url: string = "https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=10"): Promise<NVDResponse | null> {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      console.error("Failed to fetch:", response.status, response.statusText);
      return null;
    }

    const data: NVDResponse = await response.json();
    return data;
  } catch (error) {
    console.error("Error fetching data:", error);
    return null;
  }
}

export function formatCVEItems(data: NVDResponse): CVEItem[] {
  if (!data.vulnerabilities) return [];

  return data.vulnerabilities.map((item) => {
    const englishDescription = item.cve.descriptions.find(d => d.lang === 'en')?.value ||
                               item.cve.descriptions[0]?.value ||
                               'No description available';

    return {
      id: item.cve.id,
      sourceIdentifier: item.cve.sourceIdentifier,
      published: new Date(item.cve.published).toLocaleDateString(),
      lastModified: new Date(item.cve.lastModified).toLocaleDateString(),
      vulnStatus: item.cve.vulnStatus,
      description: englishDescription,
    };
  });
}

/**
 * Generate a PDF report from CVE data
 * This creates an HTML string that can be printed to PDF or processed by a PDF library
 */
export function generatePDFReport(data: NVDResponse, cveItems: CVEItem[]): string {
  const date = new Date().toLocaleDateString();
  const totalResults = data.totalResults || cveItems.length;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>NVD CVE Scan Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #1a365d; border-bottom: 2px solid #2b6cb0; padding-bottom: 10px; }
    h2 { color: #2c5282; font-size: 14pt; margin-top: 20px; }
    .meta { background: #f7fafc; padding: 15px; border-radius: 5px; margin: 20px 0; }
    .cve-item { border: 1px solid #e2e8f0; padding: 15px; margin: 15px 0; border-radius: 5px; page-break-inside: avoid; }
    .cve-id { font-size: 14pt; font-weight: bold; color: #2b6cb0; }
    .status { display: inline-block; background: #bee3f8; color: #2c5282; padding: 3px 10px; border-radius: 3px; font-size: 10pt; margin-left: 10px; }
    .description { margin: 10px 0; line-height: 1.5; }
    .dates { font-size: 10pt; color: #666; }
    .source { font-size: 9pt; color: #999; }
    .severity-critical { color: #c53030; }
    .severity-high { color: #c05621; }
    .severity-medium { color: #d69e2e; }
    .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 9pt; color: #666; text-align: center; }
  </style>
</head>
<body>
  <h1>NVD CVE Scan Report</h1>

  <div class="meta">
    <strong>Report Generated:</strong> ${date}<br>
    <strong>Total CVEs Found:</strong> ${totalResults}<br>
    <strong>Showing:</strong> ${cveItems.length} results
  </div>

  <h2>Vulnerabilities</h2>

  ${cveItems.map(cve => `
    <div class="cve-item">
      <div class="cve-id">
        ${cve.id}
        <span class="status">${cve.vulnStatus}</span>
      </div>
      <div class="description">${cve.description}</div>
      <div class="dates">
        Published: ${cve.published} | Modified: ${cve.lastModified}
      </div>
      <div class="source">Source: ${cve.sourceIdentifier}</div>
    </div>
  `).join('')}

  <div class="footer">
    Generated by ryanwilson.io | Data from National Vulnerability Database (NVD)
  </div>
</body>
</html>
  `;

  return html;
}

/**
 * Trigger browser print to PDF
 */
export function downloadPDF(htmlContent: string, filename: string = 'cve-scan-report.html'): void {
  if (typeof window === 'undefined') return;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}